#!/usr/bin/env bash
# The second line of comment
for (( i=1; i<=100; i++ )) do
	if [ $((i % 3)) = 0 ]; then
		echo "Fizz"
	fi
	if [ $((i % 5)) = 0 ]; then
		echo "Buzz"
	fi
	if [ $((i % 5)) = 0 ] && [ $((i % 5)) = 0 ]; then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	
done
