#!/usr/bin/env bash
#This is the comment that should be present

i=1
while [ $i -le 10 ];
do
	if [ $i -eq 4 ]
	then
		echo "Bad luck"
	elif [ $i -eq 8 ]
	then
		echo "Good luck"
	else
		echo "Best School"
	fi
	((i++))
done
