#!/usr/bin/env bash
#This is the comment that should be present

hours=0
while [ $hours -le 12 ];
do
	minutes=1
	echo "Hour: $hours"
	while [ $minutes -le 59 ];
	do
		echo "$minutes"
		((minutes++))
	done
       ((hours++))
done
